name: Deploy Pipeline

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      # Baixa código
      - uses: actions/checkout@v3

      # Instala Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instala dependências
      - run: npm install

      # Executa testes
      - run: npm test
